### ISSUE TITLE
Iron trapdoors don't click open (again?)

### ISSUE THREAD

**Issue by mrcoffee1026** [Tsuser1/Modern-LWC#103]
**LWC Version (/lwc admin version):** 
2.1.2-dd8c289
**Server version (/version):** 
git-Paper-621
**Short five word summary of issue:** 
protected iron trapdoors won't right click open (can be punched open only)
**Detailed description of problem:**
Saw a note this was fixed in build something like #37 which doesn't exist in the build server so this probably got rebroken somewhere along the lines.

**Comment by pop4959** [comment]
Sorry for the confusion, this was fixed in cf3052c0d7da7ee8635e3b4d2ed23ebaaec74d8e, which was included in LWC 2.1.3. If I recall correctly, it was broken in 2.1.2 due to an oversight in c0ae10aab62d3300a5fe104103eb7f0373b044a4.

The details probably don't matter to you too much, so I will spare them. The fix is to use the latest build for MC 1.13, which can be found here: https://ci.zeusmainframe.ml/job/modern-lwc/job/main/18/

We'll be posting this version to Spigot as soon as possible, however we wanted to avoid doing so for now since it might confuse people thinking it is an update for 1.14 (which are the newer dev builds). We'll probably upload both to Spigot around the same time.

I hope that makes sense now, let me know if you have any further questions!
