### ISSUE TITLE
Server Shutdown Hung on LWC Flushing Protection Updates

### ISSUE THREAD

**Issue by SurvivalQuest** [Tsuser1/Modern-LWC#108]
LWC v2.1.3-dev-288b1bf
Paper 1.13.2 b624

When shutting down the server, it is hung on LWC.

[18:39:51 INFO]: Stopping the server
[18:39:51 INFO]: Stopping server
[18:39:51 INFO]: [LWC] Disabling LWC v2.1.3-dev-288b1bf
[18:39:51 INFO]: [LWC] Flushing protection updates (32364)

This has happened a few times when we stop the server, and it does not seem to finish.
I've let it sit for 30 minutes before finally having to force kill the task.

Config: https://pastebin.com/Nv2nKQW8

**Comment by pop4959** [comment]
Every time I've been met with this problem, it has been due to a database issue (usually the MySQL server being slow or unresponsive). Normally, protections are flushed (saved) to the database while the server is running. With 32,364 that have not been flushed, is your database even connected at all?

I would urge you to investigate the following:
1) if you run the server, and place some protections down, then shut down the server, do you continue to have this issue? if so, the database was probably not connected to begin with
2) if this only occurs rarely/randomly, try to figure out when/why it happens and if the database connection remained intact or not
3) you can try using sqlite instead of mysql, which avoids needing to have a server and connection established, and see if that works

Hope that helps.

**Comment by SurvivalQuest** [comment]
The database remains up and running and is never periodically brought down.
It is running on my localhost and I have other plugins that connect to it and use it with no issues.

1. I placed some protections just now and saw them insert live into the database table. I then shut down the server and there was no flushing ([LWC] Flushing protection updates (0)), meaning the database was connecting and updating properly.

2. The database connection is always available. The plugin itself seems to have an issue with updating the database with the entries, OR thinking that it did not insert them for some odd reason when it actually did, because I do see insertions to the protections table up to a few hours before I shut the server down yesterday. So I am not sure why it was hung on flushing 32k entries that time, when the database table had been updating fine the whole time the server was up.

**Comment by pop4959** [comment]
Strange. So it's still saved all 32k protections despite hanging at the end? I don't know what could be the issue then. I don't know enough about how LWC actually handled the connection and/or flushing the protections to really give a sufficient answer right now. I may look into it as soon as I get time.

Ideally, if you can provide a means to re-produce this issue, I may be able to track it down and fix it. That would be the fastest way. It's hard to fix otherwise, as I've used LWC for 8 years and have yet to encounter this problem. For now, I suppose interrupting the server works, but it's potentially unsafe as other plugins and/or the server might not shut down properly.

**Comment by AustinGarrettRichards** [comment]
I am having the exact same problem. The database is definitely connected, but the server gets hung for 2-3 hours on flushing protection updates.

```
[05:16:10] [Server thread/INFO]: [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
[05:16:10] [Server thread/INFO]: [PlayerVaults] Disabling PlayerVaults v4.1.0
[05:16:10] [Server thread/INFO]: [XRayHunter] Disabling XRayHunter v1.2.0
[05:16:10] [Server thread/INFO]: [LWC] Disabling LWC v2.1.2-dd8c289
[05:16:10] [Server thread/INFO]: [LWC] Flushing protection updates (30175)
```

This didn't use to be an issue. Using MySQL, on the local machine. It's up and connected.

**Comment by pop4959** [comment]
Unfortunately "it happens for me too" will not get it fixed. As I mentioned before, this will not likely be fixed until someone discovers how to reproduce the issue reliably. Also, it seems apparent that it is only an issue with certain people's MySQL databases.

**Comment by AustinGarrettRichards** [comment]
I migrated our LWC database to sqlite, and it actually still occurred with 19,000 updates to flush.
It's apparently not flushing before shutdown at the interval as it should I guess?

**Comment by AustinGarrettRichards** [comment]
I had to disable history to get it to work correctly.

**Comment by pop4959** [comment]
Thanks for finding the issue! I'll keep this in mind if anyone else asks about this. The history module seems to cause a lot of pain for some people, and it isn't really required in any capacity for the plugin to work correctly.
