### ISSUE TITLE
1.13 - Armor Stands do not auto-register

### ISSUE THREAD

**Issue by Platinteufel** [Tsuser1/Modern-LWC#15]
**LWC Version (/lwc admin version):** 

2.1.0-dev-8f0b3a1/

**Server version (/version):** 

git-Spigot-2440e18-997d378 (MC: 1.13.1)

**Detailed description of problem:**

In 1.13 I got the problem that armor stands don't get locked when they're placed. I've added those entries to core.yml:

ARMOR_STAND:
   enabled: true
   autoRegister: private
LEGACY_ARMOR_STAND:
   enabled: true
   autoRegister: private

I can lock them manually by using the **/lock** command tho.

**Comment by Platinteufel** [comment]
That's weird: If I place them very fast, a few of them seem to auto-lock. 
https://youtu.be/XVuB0YsPeFA

**Comment by pop4959** [comment]
I was able to successfully reproduce this issue. Auto-registering seems to be working as intended, however the bug seems to occur when placing the armour stands from a distance. I think this was broken by a change that the previous maintainer made before he quit working on this plugin, as I have a hunch I know what it might be.

My config.yml entry:
```
        ARMOR_STAND:
            enabled: true
            autoRegister: private
```

Extra note: LEGACY_MATERIAL values are not supported. Please refrain from using them.

Confirmation of the bug: [https://gyazo.com/35aefa161de8f6fcbe7c90b5d6dee92a](https://gyazo.com/35aefa161de8f6fcbe7c90b5d6dee92a)

**Comment by pop4959** [comment]
Fixed auto-registering armour stands from a distance, in the latest dev build.
