### ISSUE TITLE
Request: Expire locks based on inactivity of users

### ISSUE THREAD

**Issue by LHammonds** [Tsuser1/Modern-LWC#32]
**LWC Version (/lwc admin version):** 
2.1.0

**Server version (/version):** 
Spigot 1.13.1

**Short five word summary of issue:** 
Expire locks based on user inactivity

**Detailed description of problem:**
Would like the ability to expire (unlock) existing locks for users that have not logged into the server for a specific # of days (config setting).  How the settings are named or command used is up to you but below are some example suggestions.

To avoid potential abuse by admins, might include a special permission node in order to run the command that can override the pre-defined "ExpirationDays" variable...or only allow the override command at the console.

An added bonus feature would be the ability to send a single mail message to the user when their locks are removed.  Since mail is not a base feature, it might be wise to include the mail command in the config settings to allow for the various mail plugins.  If settings is empty, then assume no mail is to be sent.

Example config variables:

** Expiration feature can be globally disabled or enabled.
UseExpiration = TRUE
** Default number of days a user can be inactive before locks expire.
ExpirationDays = 90
** Bonus feature: Inform player that their locks were expired.
MailCmd = mail send %PLAYER Your locks were expired due to being inactive for %ExpirationDays days.

Example admin commands:

** Expire locks based on settings in the config:
/lwc admin expirelocks

** Expire locks based on command (bypass config setting)
/lwc admin expirelocks 60

**Comment by pop4959** [comment]
I'm not sure this is necessary. There should already be an "/lwc admin expire" command that removes all inactive protections by players, according to the [wiki](https://github.com/Tsuser1/Modern-LWC/wiki/Protection-cleanup), Although, there is a subtle difference in that it only removes protections that have not been accessed in some amount of time.

Note that this subtlety is important in LWC due to the concept of shared locks. If you were to delete all protections of some player, it would also delete any locks they own that are shared. The "/lwc admin purge" command already exists to handle this case, if you are absolutely sure you want to destroy all protections of a player without checking for shared locks.

For the reasons stated above, I do not see any reason why you would want to automatically force an unsafe removal of protections by inactive players. It just sounds like a really bad idea. Players using shared protections will get very upset when suddenly those contents can be stolen from. The expire command already ensures that all inactive protections are removed, while also not removing shared locks.

**Comment by pop4959** [comment]
See my reasoning above for why this was closed. Please use `/lwc admin expire` to remove inactive protections, and `/lwc admin purge` to remove specific players, if necessary.

**Comment by LHammonds** [comment]
I already understood the scenario you are calling "unsafe" regarding shared locks.  I consider it more unsafe to unlock an active players locks simply because they have not opened every chest they own on a regular basis.

If a player is active, I do not want any of their chests to be expired regardless if they have not been in that chest for a while.  Can you see how "active" players can get upset if their locks are expired because they did not open a chest?  If people are sharing locks, they should understand that if locks can expire based on user activity, that they should be careful about who they are sharing with.  Same goes for anything that includes ability to expire protections.  I'm not asking to implement this as a default behavior.  Just in a way that I can run my server based on "player" activity.

Just looking for a way to automate the expiration of locks for inactive players...regardless if that player shared his locks.  My players can tell how long it has been since another has been online since it is critical information for faction kicks and protection expiration.

I am sure I can compile a list of inactive users in a Linux script and force feed it to the console using the "/lwc admin purge playername" but was hoping for a cleaner way to do so.

Thanks,
LHammonds

**Comment by pop4959** [comment]
@LHammonds Thank you for the detailed response! :)

You make a good point, I overlooked that. I guess removing protections is unsafe in general. However, if players on your server would not be disturbed by this, then I suppose you can feel free to do so.

I guess I may still look into this sometime. Although, for now, making a script is a great idea, and should work wonderfully!
