### ISSUE TITLE
Request: Notify upon opening unlocked chests

### ISSUE THREAD

**Issue by HeadlessJoey** [Tsuser1/Modern-LWC#35]
**LWC Version (/lwc admin version):** 
LWC version 2.1.1-dev-b78f218 (I keep trying all dev builds)

**Server version (/version):** 
1.13.1 Spigot (latest git-Spigot-500ff5d-7033f18)

**Short five word summary of issue:** 
"Request" notify when opening an unlocked chest

**Detailed description of problem:**
There already is a notify permission that tells the player who the protected chest belongs to when opened. I want the opposite which will tell the player a message (preferable configurable) that the chest is not protected.
If that is not possible so be it. Personally I found that too many people have lots and lots of chests and they always tend to forget to lock one or two chests which then get stolen from and mayhem follows.
If this is possible would it take long to add? (otherwise we might need to look into something different ourselves to notify the players somehow)

**Comment by HeadlessJoey** [comment]
That is not exactly what we want. The server has many communities in it so around 50% of the chests aren't supposed to be locked and the other 50% is personal chests that they lock by themselves. 
Our server is also very old and autolocking chests would cause a lot of confusion and it would take a long time to teach every player that they have to unlock their chests to make them public and that they don't have to do anything after placing their chests to protect them.
Sorry if that's confusing, our server is a bit different from most ^^

**Comment by pop4959** [comment]
Ah, well then I suppose you have good reason not to auto-register the protections. Although, by doing this you may be confusing your players, since many may be familiar with vanilla LWC, and expect the chests to auto-register as they do on most servers.

My personal advice would be to make it more clear to players how they should protect blocks on your server. Then players shouldn't be confused. I don't think anything much can be done on the side of LWC in terms of making it less confusing. You either have auto-register off, and tell players to use "/lock", or have auto-register on, and tell players to use "/unlock" and "/cmodify". Adding an additional notification won't help much, and therefore I do not think this is worth adding. I do recommend having auto-register on though, if your server can afford the change. This prevents the issue of players' chests being unlocked without their awareness.

I hope that helps! Please join the Discord server if you would like to chat more about this.
