### ISSUE TITLE
autoRegister: false doesn't work

### ISSUE THREAD

**Issue by Mario359** [Tsuser1/Modern-LWC#38]
**LWC Version (/lwc admin version):** 
Modern LWC 2.1
**Server version (/version):** 
Paper 271 - Minecraft 1.13.1

**Short five word summary of issue:** 
configuration, permissions, plots, auto-protect

**Detailed description of problem:**
Already, in core.yml `autoRegister: false` does not work if you leave the `autoRegister: private` (or public) line for a block
So I deleted the `autoRegister: private` line from all blocks
Then, the plugin doesn't work with PlotSquared or LuckPerms I don't know
I have disabled lwc.* permission for my plot world and players cannot use the chests they have placed in their plots
The message: The server admin does not allow you to open this (a red message from LWC)

**Comment by pop4959** [comment]
You are reporting more than one issue. I would appreciate if you can make several issues instead of putting them all here. Mixing them makes it really hard to understand what your problem with each of them are.

Using "autoRegister" on a block will cause it to lock automatically when players place it. You can add or remove this from each block to have it work the way you want it to.

LWC should work perfectly fine with LuckPerms. You shouldn't be using a negative wildcard though, or players will not have access to their chests.

I don't know anything about PlotSquared, but it's a fairly popular plugin and no one has reported issues with it working with LWC.

I am closing this issue now. Please make a new one for each problem you still have, if I have not answered them already above. Also, be much more descriptive! Saying "It doesn't work" will not help fix it. Thanks!
