### ISSUE TITLE
Long shutdown time

### ISSUE THREAD

**Issue by jordanwilliams1** [Tsuser1/Modern-LWC#40]
During shutdown the server takes ages to shutdown because of LWC,

Running latest papermc
runninng #2​1 https://ci.zeusmainframe.ml/job/modern-lwc/job/main/
https://i.gyazo.com/66c0447adcee63039e043e376ade63b5.png

**Comment by pop4959** [comment]
Can you link me a copy of your config on [hastebin](https://hastebin.com/) and paste the output of "/lwc admin version" as well. This might help assist in figuring out what is wrong. You might also want to try running LWC with a default config file. I have never seen that many protections being flushed on shutdown.

**Comment by pop4959** [comment]
Chatted on Discord, and it seems like this is not really an issue with LWC. It looks like the issue is just that the server is running extremely slow, and so protection updates aren't able to be queued until later (such as at shutdown). Normally, I have never seen more than 10 updates getting flushed on shutdown, so this should not be a problem for any properly optimised server.
