### ISSUE TITLE
Problem crash with furnace

### ISSUE THREAD

**Issue by Raphy123** [Tsuser1/Modern-LWC#57]
**LWC Version (/lwc admin version):**  latest
**Server version (/version):** 1.13.2

**Short five word summary of issue:** 

Hi

When a player light a furnace, server crash few seconds later

**Detailed description of problem:**
When i disable LWC, bug disappears

**If there was an error in console, put it here:**

https://pastebin.com/1pyuWHmy
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
@Raphy123 Try to remove all plugins except for LWC and see if the issue persists. Nowhere in the errors does LWC show up, so it is probably not related to this plugin. Feel free to make a new ticket if you believe you have evidence against that. If you do, be sure to properly fill in all information so that we're capable of investigating this issue.
