### ISSUE TITLE
Issue with Orebfuscator

### ISSUE THREAD

**Issue by GershonR** [Tsuser1/Modern-LWC#73]
**LWC Version (/lwc admin version):**  1.9.4
**Server version (/version):** `Paper version git-Paper-1589 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

**Short five word summary of issue:** Players can access locked chests when using orebfuscator.

**Detailed description of problem:**
If you are using Orebfuscator, and chests appear as stone, if you are quick enough and spam right click, you can access the chest and modify its contents. An easy way to do this is way up to a chest, and teleport away, i.e /spawn or /home, and come back with /back and spam right click. When I disable Orebfuscator the chests are protected fine.

**Comment by pop4959** [comment]
@GershonR This is a bug with Orebfuscator. As you mentioned, the problem is fixed if you remove the plugin. Please report it to them instead.

**Comment by GershonR** [comment]
LWC locks the actual block and knows it's location, how would Orebfuscator fix this if its only changing the block type of the chest and is not responsible for the locking of it?

**Comment by pop4959** [comment]
@GershonR LWC can't be held accountable for other plugins behaving irresponsibly. Orebfuscator may be cancelling the event that LWC requires to check permissions of locked blocks. Or, since it is using ProtocolLib, it could be intercepting packets and providing fake information to the event.

It is not LWC's fault for this, nor is it even possible to correct on our side. Your solution is to have Orebfuscator fix their plugin, or use a different anti-xray plugin.

**Comment by ProgrammerDan** [comment]
Look, please, this isn't an Orebfuscator issue. 

See related in Citadel, a similar block protection plugin, and how we fixed it -- hint -- it was a malformed Clientside packet, exploitable (and is exploited by hacked clients) ... only thing orebfuscator is guilty of, is making it so that otherwise well-behaved clients can create this packet by accident, which hacked clients can do at will.

https://github.com/DevotedMC/Citadel/issues/54 -- and the PR that fixed it -- https://github.com/DevotedMC/Citadel/pull/55

Hope that helps.

Orebfuscator does not change the world, period.

**Comment by ProgrammerDan** [comment]
To be specific, this line here:

https://github.com/megoesrawr/Modern-LWC/blob/master/src/main/java/com/griefcraft/listeners/LWCPlayerListener.java#L635

Looks a lot like what got us in trouble with Citadel. 

The malformed packet our dogged investigator found, basically triggers a USE but with the wrong hand, which shouldn't be possible, but is in both hacked clients and in the weird-state that Orebfuscator inadvertently unlocks. Remove this over-optimization and the problem will go away.

**Comment by GershonR** [comment]
There isn't any special configuration required, you just need both plugins and be able to teleport to and from a locked chest / protected block, making sure the chunk gets unloaded. It would be more interesting to test this with some sort of cheat client that replicates the orebfuscator behavior by changing the chest to another block.

**Comment by pop4959** [comment]
@GershonR Sorry for the long delay. We were having issues with the build server, and additionally life has been busy for me. Everything should be resolved now, however. I confirmed the bug, as well as that it should now be fixed in the latest development build.
