### ISSUE TITLE
Lag spike when creating protection

### ISSUE THREAD

**Issue by vlakreeh** [Tsuser1/Modern-LWC#79]
**LWC Version (/lwc admin version): 2.1.1-46e9fa0** 
**Server version (/version): Paper version git-Paper-447 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)** 

Lag spike when creating protection

I'm currently getting large lag spikes (nearly 100ms) every time a protection is created. I'm using the sqlite adapter a default cache size. I'm not sure what else to do except potentially migrate to mysql.

**Comment by pop4959** [comment]
@vlakreeh Is the load on your disk very high? I don't see any reason why a query would be taking 100ms.

**Comment by vlakreeh** [comment]
The disk load is normal and from what I can tell isn't the bottleneck.

**Comment by pop4959** [comment]
It's not a known issue at this time. It may be better for you to join our Discord support channel for help with this, since it is probably not a bug. It will be much easier that way. You can find the link [here](https://github.com/Tsuser1/Modern-LWC#support).

**Comment by pop4959** [comment]
Confirmed not a bug. The disk was the bottleneck (slow HHD instead of SSD, as well as below average processor core count, resulting in poor read/write performance). Solution was to use MySQL, although for future reference SSDs are recommended for better server performance (not only for LWC, but also native MC world and chunk I/O).
