### ISSUE TITLE
lwc admin cleanup

### ISSUE THREAD

**Issue by seema84** [Tsuser1/Modern-LWC#89]
Version: 2.1.3-dev-e9744bb

we had already talked about this several times
on spigot (it works with papger ) the cleanup command crash the server if the database is big enough

the reason is some not synced stuff since 1.13 (paper makes it asynchron)

**Comment by pop4959** [comment]
Yep, known issue. For now the workaround is to use a Paper server to handle the cleanup, whether you normally use it or not. This issue is caused by asynchronous chunk loading, which is not supported in CraftBukkit/Spigot servers anymore due to recent updates to the vanilla server code, but is supported by Paper.

I have already made an attempt to implement a workaround to this, but it looks like it might require a rewrite of the module to have it work again. Something to look into soon again, hopefully.

**Comment by pop4959** [comment]
Just adding "open to pr" tag, in case someone has an idea of how to fix this and wants to implement it before I get around to it.

**Comment by Brokkonaut** [comment]
https://github.com/Brokkonaut/LWCEntityLocking/blob/master/src/main/java/com/griefcraft/modules/admin/AdminCleanup.java

I can not pr it, because I have a lot of different changes in my fork, but I fixed the cleanup logic there some time ago - so maybe its useful for someone.

**Comment by pop4959** [comment]
@Brokkonaut Thanks for the link, but would you mind explaining the scope of your changes? Most importantly, does it fix the issue mentioned above (using Spigot to clean up in 1.13)? The most notable difference I see is that you're calling the cleanup thread from the Bukkit scheduler instead. I would appreciate the clarification, seeing as it looks like you would rather not PR this yourself (you are more than welcome to do this however).

**Comment by Brokkonaut** [comment]
This part should be moved to the synchronized area https://github.com/Tsuser1/Modern-LWC/blob/master/src/main/java/com/griefcraft/modules/admin/AdminCleanup.java#L250-L260

Another thing is that the entity cleanup will not work (it will delete protections of existing entities), because world.getEntities() will only return entities in currently loaded chunks. Thats why I completely removed entities cleanup (fixing it would require to load all chunks in the world)

And a thing that may help to avoid server hangs is that the cleanup threads waits for free memory https://github.com/Brokkonaut/LWCEntityLocking/blob/master/src/main/java/com/griefcraft/modules/admin/AdminCleanup.java#L144-L146 Otherwise the server might run out of memory, because it might has to load a lot of chunks.

**Comment by pop4959** [comment]
Thank you for the additional notes. I will try to take a look at this in the next few days, provided I'm not too busy with coursework.

**Comment by pop4959** [comment]
Surprise! I ended up being really busy and never got back to this large issue. However, it looks like it has resolved itself in 1.14. I'll personally refer back to this issue if the problem arises again and the cleanup module needs to be refactored/rewritten.
