### ISSUE TITLE
Permissions bug with donation tests.

### ISSUE THREAD

**Issue by andrewkm** [Tsuser1/Modern-LWC#90]
I block donation chest permissions.
/cdonation - successfully blocked.
/lock donation - is a bypass

rip.

tl;dr /lock donation doesn't check for lwc.create.donation
verbose: https://pastebin.com/raw/TqPif4QM

version: compiled on https://github.com/Tsuser1/Modern-LWC/commit/e9744bb21d4818b1218c2c8fe2f853c5af471d9b
build 7: https://ci.zeusmainframe.ml/job/modern-lwc/job/dev-builds/7/

**Comment by pop4959** [comment]
Confirmed. It looks like the "donation" parameter for /lock does not respect the correct permission. Will fix.

**Comment by pop4959** [comment]
It looks like the problem was that /lock creates a private chest, and when the "donation" parameter is added, it performs a rights modification, changing the type of the chest. There was actually no permission check on this modification, so it would simply allow anyone to do this.

The latest development build should fix this issue.
